# Generated by Django 3.0.5 on 2020-04-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_image',
            new_name='cover_img',
        ),
    ]
